/*O_o*/
google.visualization.Query.setResponse({
  version: "0.6",
  reqId: "0",
  status: "ok",
  sig: "2136996263",
  table: {
    cols: [{ id: "A", label: "Title ", type: "string" }],
    rows: [
      { c: [{ v: "La notte" }] },
      { c: [{ v: "Il sorriso" }] },
      { c: [{ v: "Scorre" }] },
      { c: [{ v: "A volte... onde" }] },
      { c: [{ v: "Lucente" }] },
      { c: [{ v: "Niente..." }] },
      { c: [{ v: "La fiamma si spegne" }] },
      { c: [{ v: "Milioni di onde" }] },
      { c: [{ v: "Ultima volta" }] },
      { c: [{ v: "Piove" }] },
      { c: [{ v: "Il pensiero" }] },
      { c: [{ v: "L\u0027oscurità" }] },
      { c: [{ v: "Sul filo di lana" }] },
      { c: [{ v: "Profonda...mente" }] },
      { c: [{ v: "Sicuro?" }] },
      { c: [{ v: "Cos\u0027è successo" }] },
      { c: [{ v: "Dove sei" }] },
      { c: [{ v: "Gocce" }] },
      { c: [{ v: "I tuoi capelli" }] },
      { c: [{ v: "Noi due" }] },
      { c: [{ v: "La vita e la morte" }] },
      { c: [{ v: "E\u0027 tempo" }] },
      { c: [{ v: "La meta" }] },
      { c: [{ v: "L\u0027inizio" }] },
      { c: [{ v: "Il dolore" }] },
      { c: [{ v: "Trafalgar square" }] },
      { c: [{ v: "Lontano" }] },
      { c: [{ v: "Il suo amore" }] },
      { c: [{ v: "Il dono ricevuto" }] },
      { c: [{ v: "Angelo biondo" }] },
      { c: [{ v: "La mia vita" }] },
      { c: [{ v: "Io scrivo" }] },
      { c: [{ v: "Ogni mattina" }] },
      { c: [{ v: "In questo momento" }] },
      { c: [{ v: "Io e te" }] },
      { c: [{ v: "Volere" }] },
      { c: [{ v: "A Mirian" }] },
      { c: [{ v: "Il sogno" }] },
      { c: [{ v: "Rosanna" }] },
      { c: [{ v: "Il carnevale" }] },
      { c: [{ v: "La vita" }] },
      { c: [{ v: "Splendida giornata" }] },
      { c: [{ v: "Alla ricerca" }] },
      { c: [{ v: "Venerdì" }] },
      { c: [{ v: "La fine" }] },
      { c: [{ v: "Mi manca" }] },
      { c: [{ v: "Dio" }] },
      { c: [{ v: "Io...solo" }] },
      { c: [{ v: "La notte" }] },
      { c: [{ v: "La rana" }] },
      { c: [{ v: "Parigi" }] },
      { c: [{ v: "Pensa" }] },
      { c: [{ v: "Sensazioni" }] },
      { c: [{ v: "Amore" }] },
      { c: [{ v: "Che ne sai" }] },
      { c: [{ v: "Dolce fiore" }] },
      { c: [{ v: "Fratello" }] },
      { c: [{ v: "Che bei momenti" }] },
      { c: [{ v: "Un sole amaro" }] },
      { c: [{ v: "Mi ritrovo" }] },
      { c: [{ v: "Mi piacerebbe..." }] },
      { c: [{ v: "Il tuo nettare" }] },
      { c: [{ v: "Notti lontane" }] },
      { c: [{ v: "O tango" }] },
      { c: [{ v: "Giorno x Giorno" }] },
      { c: [{ v: "Basta!" }] },
      { c: [{ v: "Non voglio più" }] },
      { c: [{ v: "E\u0027 giunto il tempo" }] },
      { c: [{ v: "Il mio libro" }] },
      { c: [{ v: "Il mio stato" }] },
      { c: [{ v: "Ancora pensieri " }] },
      { c: [{ v: "Là fuori" }] },
      { c: [{ v: "Ancora breccia" }] },
      { c: [{ v: "Er nasone" }] },
      { c: [{ v: "Mattatoio" }] },
      { c: [{ v: "Un giorno ricorrente" }] },
      { c: [{ v: "Una poesia" }] },
      { c: [{ v: "Maracanà" }] },
      { c: [{ v: "Navigo" }] },
      { c: [{ v: "Prima ancora" }] },
      { c: [{ v: "La raccolta" }] },
      { c: [{ v: "Due uova" }] },
      { c: [{ v: "Salti" }] },
      { c: [{ v: "Il diario" }] },
      { c: [{ v: "In viaggio" }] },
      { c: [{ v: "L\u0027uomo imperfetto" }] },
      { c: [{ v: "Il viaggio" }] },
      { c: [{ v: "Il sesto senso" }] },
      { c: [{ v: "Tra i boschi" }] },
      { c: [{ v: "Il lenzuolo" }] },
      { c: [{ v: "La mano nel sasso" }] },
      { c: [{ v: "Il Mio Pensiero" }] },
      { c: [{ v: "Ciao NOA" }] },
      { c: [{ v: "A Massimiano" }] },
      { c: [{ v: "Immerso nel buio" }] },
      { c: [{ v: "Ma..ssi...Lì..lì" }] },
      { c: [{ v: "Confuso" }] },
      { c: [{ v: "il vento trasportato via dalla pioggia" }] },
      { c: [{ v: "Bonnie" }] },
      { c: [{ v: "Fuma!" }] },
      { c: [{ v: "Pensieri tristi" }] },
      { c: [{ v: "In arrivo" }] },
      { c: [{ v: "La signora" }] },
      { c: [{ v: "Il tempo" }] },
      { c: [{ v: "Partenza..." }] },
      { c: [{ v: "Il mattino" }] },
      { c: [{ v: "Fiocchi di neve" }] },
      { c: [{ v: "Una guerra!" }] },
      { c: [{ v: "Il mio intorno" }] },
      { c: [{ v: "Caro Monti, #SalvaiCiclisti" }] },
      { c: [{ v: "La prima Bike Square d\u0027Italia" }] },
      { c: [{ v: "La notte" }] },
      { c: [{ v: "A spasso" }] },
      { c: [{ v: "Il sogno" }] },
      { c: [{ v: "Narciso" }] },
      { c: [{ v: "Il volo dell\u0027aliante" }] },
      { c: [{ v: "La ruota" }] },
      { c: [{ v: "La Rota fixa" }] },
      { c: [{ v: "La striscia" }] },
      { c: [{ v: "Scorri-bande" }] },
      { c: [{ v: "Perso!" }] },
      { c: [{ v: "Il sogno" }] },
      { c: [{ v: "Nuove sfide" }] },
      { c: [{ v: "Come il tempo" }] },
      { c: [{ v: "Dicembre" }] },
      { c: [{ v: "Il senso della vita" }] },
      { c: [{ v: "La Primavera" }] },
      { c: [{ v: "La Famiglia" }] },
      { c: [{ v: "Percorsi" }] },
      { c: [{ v: "Se Tu.." }] },
      { c: [{ v: "Una farfalla..." }] },
      { c: [{ v: "Vado di fretta" }] },
      { c: [{ v: "7 anni: la raccolta" }] },
      { c: [{ v: "7 anni" }] },
      { c: [{ v: "1919-2015" }] },
      { c: [{ v: "Il teatro" }] },
      { c: [{ v: "Il sogno" }] },
      { c: [{ v: "Ho perso il contatto" }] },
      { c: [{ v: "Il sogno che finisce" }] },
      { c: [{ v: "Incalzante" }] },
      { c: [{ v: "Svegliarsi" }] },
      { c: [{ v: "La vita in una mano" }] },
      { c: [{ v: "Sunflowers" }] },
      { c: [{ v: "The life train" }] },
      { c: [{ v: "Sunny sky" }] },
      { c: [{ v: "Il camino acceso" }] },
      { c: [{ v: "Il clown" }] },
      { c: [{ v: "Ogni giorno" }] },
      { c: [{ v: "Loosing time" }] },
      { c: [{ v: "The life you like" }] },
      { c: [{ v: "Il treno della vita - Un Sacco di vita" }] },
      { c: [{ v: "La bici va" }] },
      { c: [{ v: "La venere dorata" }] },
      { c: [{ v: "All\u0027improvviso" }] },
      { c: [{ v: "Bene e male" }] },
      { c: [{ v: "O Luna..." }] }
    ],
    parsedNumHeaders: 0
  }
});
